### ISSUE TITLE
You should not panic(err)

### ISSUE THREAD

**Issue by snwfdhmp** [jony4/bulletdb#1]
https://github.com/jony4/bulletdb/blob/e4765d431f9a3f03da12afff4ebf763755158bfb/apps/cms/storage/storage.go#L15-L20

Hey dude,

Just a friendly advice. You should not panic(err). You should use [a package like this](https://github.com/snwfdhmp/errlog) for debugging your errors. Debug your code with :

1. Clear stack trace
2. Failing func call highlighting

<img width="999" alt="example" src="https://user-images.githubusercontent.com/23099246/53098953-11310c80-3525-11e9-8f6f-302791743cdf.png">

It’s way more easier then to debug.

Real better than panic-ing (in most case). You can still force exit if you need it.

I would be happy to get your feedbacks.

**Comment by jony4** [comment]
Thanks for your suggestions very much！

yeah, [CodeReviewComments](https://github.com/golang/go/wiki/CodeReviewComments#dont-panic) just as this code review comments,  I will change panic to another way, for example return error to top level.

and this repo (bulletdb-cms) is do something awesome: 

1. It's a cms, content management system which is writed in Golang
2. It allow you add your custom content type, "news" "blog" "articles" etc.
3. Every content type has it's own custom field, news content type has "title", "body", "news source" etc.

Working in process, Welcome to join us ! ^_^
